### ISSUE TITLE
Hierarchical HTTP cache implementation is not working

### ISSUE THREAD

**Issue by Bfarkiani** [envoyproxy/envoy-mobile#2720]
I want to implement a Cache hierarchy. My scenario is as follows: 

I have three envoy servers chained together and one cache service at the end: Main -> Intermediate -> Final -> Service. 
For the service I am using the code provided for the cache filter here: 
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cache_filter
For the Main envoy configuration is as follows: 

```
static_resources:
  listeners:
  - name: listener_tcp
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                #return 503 after 20s
                  timeout: 0s
                  retry_policy:
                      retry_on: 5xx,refused-stream,connect-failure,gateway-error,reset,refused-stream
                      num_retries: 4
                      per_try_timeout: 5s
                  cluster: envoyInt
          http_filters:
          - name: "envoy.filters.http.cache"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig"          
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              
  clusters:
  - name: envoyInt
    connect_timeout: 5s
    type: STRICT_DNS
    load_assignment:
      cluster_name: envoyInt
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy_int
                port_value: 8001
```

Main just forwards any request to the intermediate envoy. Config of Intermediate is as follows:

```
static_resources:
  listeners:
  - name: listener_tcp
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                #return 503 after 20s
                  timeout: 0s
                  retry_policy:
                      retry_on: 5xx,refused-stream,connect-failure,gateway-error,reset,refused-stream
                      num_retries: 4
                      per_try_timeout: 5s
                  cluster: envoyFinal
          http_filters:
          - name: "envoy.filters.http.cache"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig"          
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              
  clusters:
  - name: envoyFinal
    connect_timeout: 5s
    type: STRICT_DNS
    load_assignment:
      cluster_name: envoyFinal
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy_final
                port_value: 8002
```
Intermediate forwards to Final envoy and the config of Final is as follows (very similar to cache filter example)

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8002
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service/1"
                route:
                  cluster: service1
              - match:
                  prefix: "/service/2"
                route:
                  cluster: service2
          http_filters:
          - name: "envoy.filters.http.cache"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig"
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: service1
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service1
                port_value: 8080
  - name: service2
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service2
                port_value: 8080
```
So, each envoy node can cache HTTP requests. My scenario is as follows: 
1- I send a request to Final envoy:
`curl -i localhost:8002/service/1/valid-for-minute`

2- repeat the request and see the content is cached
3- send the request to Main envoy: 
`curl -i localhost:8000/service/1/valid-for-minute`
4- I expect to see the cached response, but a new response is generated. 

I think the cache implementation acts based on the whole header instead of the original parts of the request, and since each envoy server node adds its own x-forward-id header, we do not see a cache hit.
